'''
FILL OUT ALL THE VARIABLES FOR USAGE
'''


POLYGONSCAN_API_KEY = ""
MY_USDT_WALLET = ""
USDT_CONTRACT = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
LOWEST_VALID_PAYMENT = 3

GHOST_ADMIN_API_URL_MEMBERS = "https://_.ghost.io/ghost/api/admin/members/"
ADMIN_API_KEY = "GHOST_ADMIN_API_KEY"

TOKEN = "TELEGRAM_BOT_TOKEN"
SERVICE_NAME = "YOUR_SERVICES_NAME"
OUR_WALLET = "OUR_USDT_WALLET_ADDRESS"
BOT_NAME = "BOT_NAME"
